# Generated by Django 5.2.7 on 2025-10-31 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_borrowrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='課程名稱')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='課程號碼')),
                ('instructor', models.CharField(max_length=100, verbose_name='任課老師')),
            ],
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='user',
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midtrem_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='期中成績')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='期末成績')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.course', verbose_name='課程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='學生')),
            ],
            options={
                'verbose_name': '選課紀錄',
                'verbose_name_plural': '選課紀錄管理',
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BorrowRecord',
        ),
    ]
