# Generated by Django 6.0 on 2026-01-06 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_remove_course_instructor_teacher_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='期末成績'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='midtrem_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='期中成績'),
        ),
    ]
