# Generated by Django 6.0.1 on 2026-01-09 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _migrate_teacher_fk_to_user(apps, schema_editor):
    Course = apps.get_model('grades', 'Course')
    Teacher = apps.get_model('grades', 'Teacher')
    # Map existing Course.teacher (Teacher PK) to the corresponding User PK
    for c in Course.objects.exclude(teacher__isnull=True):
        try:
            t = Teacher.objects.get(pk=c.teacher_id)
            c.teacher_id = t.user_id
            c.save()
        except Teacher.DoesNotExist:
            # If referenced Teacher is missing, set to NULL
            c.teacher_id = None
            c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0007_alter_enrollment_final_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='midtrem_grade',
            new_name='midterm_grade',
        ),
        migrations.RunPython(_migrate_teacher_fk_to_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='任課教師'),
        ),
    ]
