# Generated by Django 6.0.6 on 2026-06-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_rename_midtrem_grade_enrollment_midterm_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='學分數'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='課程描述'),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(blank=True, choices=[('MWF 08:00-10:00', '週一三五 08:00-10:00'), ('TTh 10:00-12:00', '週二四 10:00-12:00'), ('MW 13:00-15:00', '週一三 13:00-15:00'), ('TTh 14:00-16:00', '週二四 14:00-16:00'), ('F 18:00-21:00', '週五 18:00-21:00')], max_length=30, verbose_name='上課時間'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='課程號碼'),
        ),
    ]
