# Generated by Django 6.0.6 on 2026-06-23 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_course_credits_course_description_course_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='審核通過'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='申請時間'),
        ),
    ]
