# Generated by Django 6.0.6 on 2026-06-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0010_enrollment_approved_enrollment_requested_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.CharField(max_length=100, verbose_name='上課時間'),
        ),
    ]
