# Generated by Django 6.0.6 on 2026-06-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0013_alter_course_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.CharField(max_length=200, verbose_name='上課時間'),
        ),
    ]
