# Generated by Django 6.0.6 on 2026-06-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0014_alter_course_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enrollment_open', models.BooleanField(default=True, verbose_name='開放選課')),
                ('is_drop_open', models.BooleanField(default=True, verbose_name='開放退選')),
            ],
            options={
                'verbose_name': '系統設定',
                'verbose_name_plural': '系統設定',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(default=40, verbose_name='課程人數上限'),
        ),
    ]
